name: flutter_cupertino_datetime_picker
description: Fork from flutter_cupertino_date_picker https://github.com/wuzhendev/flutter-cupertino-date-picker, but year, month, day seperate
version: 3.0.0
homepage: https://github.com/ocsolution/flutter_cupertino_datetime_picker.git
publish_to: none

dependencies:
  flutter:
    sdk: flutter

environment:
  sdk: ^3.5.4
